In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# create a StandardScaler object for the output layer
output_scaler = StandardScaler()

# fit the output_scaler to the training output data
train_output_data = np.random.normal(size=(100, 6))
output_scaler.fit(train_output_data)

# generate some test input data
test_input_data = np.random.normal(size=(10, 21))

# use the neural network to predict the standardized output
test_std_output = np.random.normal(size=(10, 6))
test_output = output_scaler.inverse_transform(test_std_output)

# test_output contains the predicted output in its original (non-standardized) form

In [2]:
import numpy as np

# Define the original X values
X = np.array([1, 10, 100, 1000])

# Apply a log transformation to X
X_log = np.log(X)

# Define the corresponding label values
y = np.array([1, 2, 3, 4])

print(X_log)

[0.         2.30258509 4.60517019 6.90775528]


In [58]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, MinMaxScaler
from numpy import log, exp

X = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]).astype(float) * 1000
P = np.array([0, 1, 1, 1])
bases = np.array([0, 2, np.e, 10])

def log_transform(X, P, bases):
    X_new = X.copy()
    for (index, check) in enumerate(P):
        if (check == 1):
            X_new[:, index] = np.emath.logn(bases[index], X[:, index])
    return X_new

def exp_transform(X, P, bases):
    X_new = X.copy()
    for (index, check) in enumerate(P):
        if (check == 1):
            X_new[:, index] = np.exp(X[:, index] * np.log(bases[index]))
    return X_new


log_transformer = FunctionTransformer(func=log_transform,inverse_func=exp_transform, kw_args={'P': P, 'bases': bases}, inv_kw_args={'P': P, 'bases': bases})

# define the pipeline with steps for log transformation, standardization, and min-max scaling
pipeline = Pipeline([
    ('log', log_transformer),
    ('standardize', StandardScaler()),
    ('min_max_scale', MinMaxScaler(feature_range=(0, 1))),
])

pipeline.fit(X)

print(X)
# apply the pipeline to a feature matrix X
X_transformed = pipeline.transform(X)

print(X_transformed)

# apply the reverse pipeline to the transformed feature matrix X_transformed
X_original = pipeline.inverse_transform(X_transformed)

print(X_original)

[[ 1000.  2000.  3000.  4000.]
 [ 5000.  6000.  7000.  8000.]
 [ 9000. 10000. 11000. 12000.]]
[[0.         0.         0.         0.        ]
 [0.5        0.68260619 0.65212727 0.63092975]
 [1.         1.         1.         1.        ]]
[[ 1000.  2000.  3000.  4000.]
 [ 5000.  6000.  7000.  8000.]
 [ 9000. 10000. 11000. 12000.]]


In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, MinMaxScaler
from numpy import log, exp

# X = np.array([[1.00e+00, 2.00e+02],
#             [1.01e+00, 1.00e+01],
#             [1.00e+02, 2.00e+03],
#             [1.00e+00, 1.00e+03],
#             [1.00e-03, 2.00e+00],
#             [1.00e-03, 2.00e+00],
#             [1.00e-02, 2.50e+01],
#             [1.00e-03, 2.00e+00],
#             [1.00e-03, 3.00e+00],
#             [1.00e-03, 3.00e+00]])

X = np.array([[1.00e+00, 1.01e+00, 1.00e+02, 1.00e+00, 1.00e-03, 1.00e-03, 1.00e-02, 1.00e-03, 1.00e-03, 1.00e-03],
              [2.00e+02, 1.00e+01, 2.00e+03, 1.00e+03, 2.00e+00, 2.00e+00, 2.50e+01, 2.00e+00, 3.00e+00, 3.00e+00]])

X_one_dimension = np.array([1.00e+00, 1.01e+00, 1.00e+02, 1.00e+00, 1.00e-03, 1.00e-03, 1.00e-02, 1.00e-03, 1.00e-03, 1.00e-03])

powerTest = np.array([1, 1.3, 1.3, 1.3, 1, 1.3, 1.3, 1.3, 1.3, 1.3])

def root_transform(X, power):
    if len(X.shape) == 1:
        # X is a 1D array
        return X ** (1/power)
    else:
        # X is a 2D array
        
        return np.power(X, (1/power).reshape(1, -1))

def power_transform(X, power):
    if len(X.shape) == 1:
        # X is a 1D array
        return X ** power
    else:
        # X is a 2D array
        return np.power(X, power.reshape(1, -1))

# X_root = root_transform(X, powerTest)
# print(X_root)
# X_pow = power_transform(X_root, powerTest)
# print(X_pow)

# X_root = root_transform(X_one_dimension, powerTest)
# print(X_root)
# X_pow = power_transform(X_root, powerTest)
# print(X_pow)

poly_transformer = FunctionTransformer(func=root_transform,inverse_func=power_transform, kw_args={'power': powerTest}, inv_kw_args={'power': powerTest})

# define the pipeline with steps for log transformation, standardization, and min-max scaling
pipeline = Pipeline([
    ('poly_transformer', poly_transformer),
    ('min_max_scale', MinMaxScaler(feature_range=(0, 1))),
])

pipeline.fit(X)

print(X)
# apply the pipeline to a feature matrix X
X_transformed = pipeline.transform(X)

print(X_transformed)

# apply the reverse pipeline to the transformed feature matrix X_transformed
X_original = pipeline.inverse_transform(X_transformed)

print(X_original)

[[1.00e+00 1.01e+00 1.00e+02 1.00e+00 1.00e-03 1.00e-03 1.00e-02 1.00e-03
  1.00e-03 1.00e-03]
 [2.00e+02 1.00e+01 2.00e+03 1.00e+03 2.00e+00 2.00e+00 2.50e+01 2.00e+00
  3.00e+00 3.00e+00]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1.00e+00 1.01e+00 1.00e+02 1.00e+00 1.00e-03 1.00e-03 1.00e-02 1.00e-03
  1.00e-03 1.00e-03]
 [2.00e+02 1.00e+01 2.00e+03 1.00e+03 2.00e+00 2.00e+00 2.50e+01 2.00e+00
  3.00e+00 3.00e+00]]


In [3]:
print(2 ** 1/1.3)
print(1.5384615384615383 ** 1/(1/1.3))

1.5384615384615383
2.0
